$('#home').click(()=>{
    window.location.replace('/admin/adminhome')
})
$('#bookdata').click(()=>{
    window.location.replace('/bookcrud/data')
})
$('#logout').click(()=>{
    window.location.replace('/admin/adminlogout')
})