# Generated by Django 4.0.3 on 2022-03-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_user_book1_alter_user_book2_alter_user_book3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='book2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='book3',
        ),
    ]
