# Generated by Django 4.0.3 on 2022-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_remove_user_book1_remove_user_book2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book1',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='book2',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='book3',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
