# Generated by Django 4.0.3 on 2022-03-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_user_book1_user_book2_user_book3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='book2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='book3',
        ),
    ]
