# Generated by Django 4.0.3 on 2022-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_remove_user_book1_remove_user_book2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='book2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='book3',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
