# Generated by Django 4.0.3 on 2022-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_user_book1_user_book2_user_book3'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_barcode',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
