# Generated by Django 4.0.3 on 2022-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bookcrud', '0002_remove_book_quantity_remove_book_quantity_indemand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
