# Generated by Django 4.0.3 on 2022-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_bookcrud', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_description', models.CharField(max_length=20)),
                ('book_image', models.ImageField(upload_to='book_pics/')),
                ('book_price', models.FloatField(max_length=20)),
                ('book_inhand', models.BooleanField(default=False)),
                ('book_author', models.CharField(max_length=20)),
            ],
        ),
    ]
