# Generated by Django 4.0.3 on 2022-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bookcrud', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
